version: "3"
services:
    backend:
        entrypoint:
            - yarn
            - watch
        ports:
            - 3001:3001
        environment:
            DATABASE_HOST: database
            DATABASE_PORT: 5432
            DATABASE_USER: worsement
            DATABASE_PASSWORD: password
            DATABASE_DATABASE: worsement
    database:
        ports:
            - 15432:5432
        volumes:
            - postgres-data:/var/lib/postgresql/data
volumes:
    postgres-data: